### ISSUE TITLE
--manifest error

### ISSUE THREAD

**Issue by illycz** [L8D/rev-all#2]
When I try generate manifest file to output folder I get:
`EISDIR: illegal operation on a directory, open '/Users/illy/Sites/_Templates/mujmastercard/deploy'`
and
```
errno: -21,
code: 'EISDIR',
syscall: 'open',
path: '/Users/illy/Sites/_Templates/mujmastercard/deploy'
```
My task: `"rev": "rev-all dist deploy --manifest deploy --dont-rename html",`

Any suggestion?

**Comment by L8D** [comment]
the path needs to be a full path to the file like `--manifest deploy/manifest.json`

**Comment by illycz** [comment]
Great, thanks. Do you now, how to exclude html files from manifest? Before I used `--dont-rename html` this is working but there is useless references in manifest. `--blacklist html` not working at all.

Thanks for reply
